### ISSUE TITLE
Add splash page to kgrid.github.io

### ISSUE THREAD

**Issue by pboisver** [kgrid/kgrid.github.io#2] opened 2017-02-20 14:37 UTC
See https://slack.com/is and

**Comment by pboisver** [comment] 2017-02-20 14:39
And a little more:
 
fedora-commons.org
www.oit.va.gov/specialreports/dhp
smarthealthit.org
 
 
https://drive.google.com/drive/search?q=knowledge%20grid%20user%20story
 
Major stakeholder groups for the Knowledge Grid:
 
+ App builders
+ Knowledge engineers – Object authors
+ Knowledge managers – Curators of objects
+ IT decision makers
+ Clinical decision makers (e.g., executive at an insurance company with an MD degree)
+ Researchers who are interested in moving their research into practice
 
PERHAPS THREE TARGET GROUPS

Techies | Biomedical Researchers | Health Practice Leaders
 



 
 
 
From: Beltran Figueroa <belfigue@umich.edu>
Date: Wednesday, February 1, 2017 at 2:41 PM
To: Peter Boisvert <pboisver@med.umich.edu>
Cc: Allen Flynn <ajflynn@med.umich.edu>
Subject: Re: Platform/ecosystem web presence
 
Thank you, both for sharing. Fascinating examples for our infrastructure and marketing design moving forward.
 
Allen, see you very soon.
 
On Wed, Feb 1, 2017 at 1:59 PM, Boisvert, Peter <pboisver@med.umich.edu> wrote:
And another example from a related source that Allen shared today: Open-EMR (Also, see below for MyAVA, an example of a product, from Open Source Health, based on Open-EMR.)
 
Open-EMR
http://www.open-emr.org/  (The open source platform that MyAVA is using. Links to the rest of the ecosystem at top and bottom; managed by the not-for-profit OEMR, www.oemr.org)
 
----
MyAVA (the product)
http://opensourcehealth.com/ (The company building a product)
https://myava.mi-squared.com/openemr/ (the product itself; link is buried in a press release, demo user name: welby, password: doctor)
 
From: Allen Flynn <ajflynn@med.umich.edu>
Date: Wednesday, February 1, 2017 at 12:04 PM
To: Beltran Figueroa <belfigue@umich.edu>
Cc: "Boisvert, Peter" <pboisver@med.umich.edu>
Subject: Re: Platform/ecosystem web presence
 
Hi Beltran –
 
   FYI – these are materials for discussion today.  To give context, we want to take an encompassing view of the Knowledge Grid’s web presence, meaning that multiple tools and sites will be involved as opposed to “building a website.”
 
  Peter has provided us with some great examples.
 
   More to come.
 
- Allen
 
 
 
From: Peter Boisvert <pboisver@med.umich.edu>
Date: Wednesday, February 1, 2017 at 11:59 AM
To: Allen Flynn <ajflynn@med.umich.edu>
Cc: "Figueroa Marquez, Beltran Jaime" <belfigue@med.umich.edu>
Subject: Platform/ecosystem web presence
 
Examples of combined branding, marketing, documentation, infrastructure, and associated content for complex products/platforms. We can build the pieces we need consistent with our brand strategy over time. The development team is just getting started on some product documentation targeted at authors and developers.
 
Atomist (automation framework)
 
https://www.atomist.com/ (splash page/marketing/value proposition; gateway to additional content)
http://docs.atomist.com/ (documentation site; generated from managed content)
https://medium.com/the-composition (product development blog; hosted on an outside platform)
https://github.com/atomist (infrastructure/code for the product; open source)
 
 
Vue (frontend framework)
 
https://vuejs.org/ (splash page…)
https://vuejs.org/v2/guide/ (guide)
https://github.com/vuejs/vue (code)
https://github.com/vuejs/awesome-vue (curated list of associated components/products)
 
https://nuxtjs.org/ (an associated independent product; shares branding)
https://vuejsfeed.com/ (an independent news source for the Vue ecosystem)
 
https://leanpub.com/vuejs2?ref=vuejsfeed.com (an independent book about the product; hosted (and monetized) separately)
 
Heroku (selling & managing comprehensive platform services for startups; providing documentation and guides for developers using the services)
 
https://www.heroku.com (splash page…including starting point for using their cloud services)
https://devcenter.heroku.com/ (targeted to developers)
https://devcenter.heroku.com/categories/heroku-architecture (in-depth architecture)
https://www.heroku.com/teams (a related service in the Heroku line of services)
https://blog.heroku.com/ (blog)
https://www.facebook.com/Heroku/ (social media)
https://status.heroku.com/ (a service status page)
 
 
-Peter

**Comment by gqmeng** [comment] 2017-03-24 17:52
Duplicate of #11

**Closed as completed** 2017-03-24 17:53 UTC
Labels: duplicate
